[package]
name = "dominoes_ai"
version = "0.1.0"
edition = "2018"
authors = ["Sebastian Garrido <sebasgarcep@gmail.com>"]

[lib]
name = "dominoes_ai"
path = "src/lib.rs"

[[bin]]
name = "validate"
path = "src/bin/validate.rs"

[dependencies]
rand = "0.8.4"